name: CI - TAF Tests Pipeline

on:

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs:
      browser:
        description: "Choose browser for UI tests"
        required: true
        default: "chrome"
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TestCase1Epam/TestCase1Epam.csproj


  api-tests:
       runs-on: windows-latest
       steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
             dotnet-version: '9.0.x'

         - name: Run API Tests
           continue-on-error: true
           run: dotnet test TestCase1Epam/TestCase1Epam.csproj --filter "Category=API" --logger "trx;LogFileName=API_TestResults.trx" --results-directory TestResults

         - name: Upload API Test Results
           uses: actions/upload-artifact@v4
           with:
             name: API_TestResults
             path: TestResults

  ui-tests:

        runs-on: windows-latest
        needs: build
        env:
         Browser: ${{ github.event.inputs.browser || 'chrome' }}
         LANG: en_us
         CI: true

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '9.0.x'

          - name: Run UI Tests (Headed mode)
            continue-on-error: true
            run: |
                   echo "Launching Chrome in headed-like mode..."
                   dotnet test TestCase1Epam/TestCase1Epam.csproj `
                   --filter "Category!=API" `
                   --logger "trx;LogFileName=UI_TestResults.trx" `
                   --results-directory TestResults `
                   /p:Browser=${{ env.Browser }} `
                   /p:RunHeaded=true `
                   /p:Lang=en-U

          - name: Upload UI Test Results
            uses: actions/upload-artifact@v4
            with:
              name: UI_TestResults
              path: TestResults

  evidences:
    runs-on: windows-latest
    needs: [api-tests, ui-tests]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: "TestCase1Epam/Artifacts/Screenshots/**/*.png"
          if-no-files-found: warn

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with: 
          name: ExtentReport
          path: "**/bin/Debug/net9.0-windows/Artifacts/Screenshots/"

 